name: Generate world map (self hosted linux)

on:
    schedule:
        - cron: "0 0 * * 0"
    workflow_dispatch:
        inputs:
            start_x:
                required: false
                default: "0"
            start_y:
                required: false
                default: "0"
            width:
                required: false
                default: "2048"
            height:
                required: false
                default: "2048"

permissions:
    contents: write # needed to create / update releases
    actions: read

jobs:
    build:
        runs-on: [self-hosted, Linux, X64]
        timeout-minutes: 1440

        steps:
            - uses: actions/checkout@v4
            - name: Create Release ID
              run: |
                  RELEASE_ID="world-$(date -u +%Y-%m-%dT%H-%M-%S.%3NZ)"
                  echo "RELEASE_ID=$RELEASE_ID" >> "$GITHUB_ENV"
                  echo "Release ID: $RELEASE_ID"
            - uses: actions/setup-node@v4
              with:
                  node-version: 24
            - run: npm ci
            - name: Configure IPv6 freebind route
              run: sudo ip -6 route replace local "${{ secrets.WPLACE_IPV6_SUBNET }}" dev lo
            - name: Archive world tiles
              run: |
                  node scripts/archive_world.ts \
                      --start-x=${{ github.event.inputs.start_x || '0' }} \
                      --start-y=${{ github.event.inputs.start_y || '0' }} \
                      --width=${{ github.event.inputs.width || '2048' }} \
                      --height=${{ github.event.inputs.height || '2048' }}
              env:
                  WPLACE_IPV6_SUBNET: ${{ secrets.WPLACE_IPV6_SUBNET }}
                  WPLACE_ARCHIVE_RPS: ${{ vars.WPLACE_ARCHIVE_RPS || '1000' }}
                  WPLACE_ARCHIVE_CONCURRENCY: ${{ vars.WPLACE_ARCHIVE_CONCURRENCY || '250' }}
                  WPLACE_ARCHIVE_SERVER_RPS_LIMIT: ${{ vars.WPLACE_ARCHIVE_SERVER_RPS_LIMIT || '4' }}
            - name: Setup Python venv
              run: |
                  python3 -m venv .venv
                  ./.venv/bin/python -m pip install --upgrade pip
                  ./.venv/bin/python -m pip install "pyvips[binary]" tqdm
            - run: ./.venv/bin/python scripts/vips.py
            - run: tar -czf tiles.tar.gz  --no-xattrs -C public/tiles .
            - name: Split archive into <2GB parts
              run: |
                  echo "Original archive size:" && ls -lh tiles.tar.gz
                  split -b 1999M -d -a 3 tiles.tar.gz tiles.tar.gz.part.
                  rm tiles.tar.gz
                  echo "Generated parts:" && ls -lh tiles.tar.gz.part.*
            - name: Upload release assets
              continue-on-error: true
              run: echo "" | gh release create ${{ env.RELEASE_ID }} -p --repo samuelscheit/wplace-archive -t ${{ env.RELEASE_ID }} tiles.tar.gz.part.* --notes-file -
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: node scripts/s3_upload_directory.ts public/tiles tiles/${{ env.RELEASE_ID }}
              env:
                  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
                  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
                  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
                  S3_REGION: ${{ secrets.S3_REGION }}
                  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
            - name: Update snapshots.json
              run: node scripts/update_snapshots.js ${{ env.RELEASE_ID }}
            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git restore package-lock.json
                  git add src/ui/snapshots.json
                  git commit -m "Update snapshots.json [skip ci]"
                  git config pull.rebase false
                  git pull
                  git push
