name: Generate world map

on:
  workflow_dispatch:
    inputs:
      release_id:
        required: true

permissions:
  contents: write   # needed to create / update releases
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Install libvips dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips libvips-dev || sudo apt-get install -y libvips42 libvips-dev
          vips --version
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: node scripts/download_archive.ts ${{ github.event.inputs.release_id }}
      - run: pip3 install -r requirements.txt
      - run: python3 scripts/vips.py
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: tiles/${{ github.event.inputs.release_id }}
          FOLDER: public/tiles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


