name: Generate world map

on:
  workflow_dispatch:
    inputs:
      release_id:
        required: true

permissions:
  contents: write   # needed to create / update releases
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Install libvips dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips libvips-dev || sudo apt-get install -y libvips42 libvips-dev
          vips --version
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: node scripts/download_archive.ts ${{ github.event.inputs.release_id }}
      - run: pip3 install -r requirements.txt
      - run: python3 scripts/vips.py
      - run: tar -czf tiles.tar.gz -C public/tiles .
      - name: Split archive into <2GB parts
        run: |
          echo "Original archive size:" && ls -lh tiles.tar.gz
          # Split into 1.9GB chunks (GitHub release asset limit is 2GB)
          split -b 1900m -d -a 3 tiles.tar.gz tiles.tar.gz.part.
          rm tiles.tar.gz
          echo "Generated parts:" && ls -lh tiles.tar.gz.part.*
      - name: Create / Update GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_id }}
          name: ${{ github.event.inputs.release_id }}
          target_commitish: ${{ github.sha }}
          draft: false
          files: |
            tiles.tar.gz.part.*
          fail_on_unmatched_files: true
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


